language: go

sudo: required

os:
    - linux
    - osx
go:
    - 1.13.x
    - 1.14.x
    - tip

matrix:
    allow_failures:
        - go: tip

script:
    make ci-test;

branches:
  only:
    - master